logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
security:
  jwt:
    token:
      secret-key: pej
      expire-length: 86400
